#!/usr/bin/env python3
# Copyright (C) 2024  Coombszy
################################################################################
# `pre-push` hook
# This is a pass through. It'll just call local hook

HOOK_NAME = "pre-push"

import subprocess
import sys
import os


# Get working repo path
def get_working_repo_path():
    return (
        subprocess.run(
            ["git", "rev-parse", "--show-toplevel"], stdout=subprocess.PIPE, check=False
        )
        .stdout.decode("utf-8")
        .strip()
    )


if __name__ == "__main__":
    exit_code = 0

    # If a local script is detected, run it if githooks was successfull
    hook_path = os.path.join(get_working_repo_path(), ".git/hooks", HOOK_NAME)
    if os.path.exists(hook_path) and exit_code == 0:
        print(f"Local {HOOK_NAME} hook detected, running...")
        result = subprocess.run(
            hook_path, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False
        )

        if len(result.stdout) > 0:
            print(result.stdout.decode("utf-8"))

        if result.returncode != 0:
            exit_code = result.returncode
    elif os.path.exists(hook_path) and exit_code != 0:
        print(f"Local {HOOK_NAME} hook detected, skipping until above is resolved")

    sys.exit(exit_code)
